// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhheygdilixbqwrfxbtt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oaGV5Z2RpbGl4YnF3cmZ4YnR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1Njc1MDYsImV4cCI6MjA1ODE0MzUwNn0.IJE-pAPztQl27c2kRJgV-iBaVb1M04WsOH9tra1aE90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);